name: BlockShuffle
version: 2.0.0
main: tech.reisu1337.blockshuffle.BlockShuffle
api-version: 26.1.2
authors: [ Reisu1337 ]
description: A Block Shuffle game for Minecraft
website: reisu1337.tech

commands:
  blockshuffle:
    description: "Open the BlockShuffle menu or stop the game"
    usage: "/<command> [stop]"

permissions:
  blockshuffle.admin:
    default: op
    description: "Allows access to the /blockshuffle command"
